#!/usr/bin/env python3
"""Applies V09's OWN stated sizing rule to real trade sequences and reports what it does.

This is NOT a test of an entry rule — V09 states none and none is invented (`D-030`).
It is the execution of a fully specified algorithm that V09 prints in full on frame
10 and states at [00:08:20]-[00:08:43]:

    2% of balance at stop, size = risk / stop_pips
    losses 1, 2, 3 -> same lot size
    loss 4         -> recalculate from the new balance
    every win      -> recalculate from the new balance

Trade sequences are regenerated by the same committed code PT-035 used
(`run_pt035.build_sequences`), same seed, so the streams are identical.

Predictions P-E1..P-E4 were committed at 97d2c1b BEFORE this file was written.
"""
import json
import os
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
BASE = os.path.dirname(HERE)
ROOT = os.path.normpath(os.path.join(BASE, "..", ".."))
sys.path.insert(0, os.path.join(ROOT, "06_MANUAL_BACKTEST", "scripts"))
sys.path.insert(0, os.path.join(ROOT, "06_MANUAL_BACKTEST", "V09"))

import mmm_lib as M          # noqa: E402
import run_pt035 as P        # noqa: E402

lines = []


def say(s=""):
    print(s)
    lines.append(s)


START = 12500.0          # V09's own worked-example balance, [00:02:25]
RISK = 0.02              # [00:02:00]


def simulate(seq, stop_pips, target_pips):
    """V09's rule, executed literally. Returns (equity_path, n_recalc_triggers)."""
    bal = START
    per_pip = (bal * RISK) / stop_pips
    losses_since_resize = 0
    triggers = 0
    path = [bal]
    for w in seq:
        if w:
            bal += target_pips * per_pip
            per_pip = (bal * RISK) / stop_pips      # recalculate after every win
            losses_since_resize = 0
        else:
            bal -= stop_pips * per_pip
            losses_since_resize += 1
            if losses_since_resize >= 4:
                per_pip = (bal * RISK) / stop_pips  # recalculate on the 4th
                losses_since_resize = 0
                triggers += 1
        path.append(bal)
    return np.array(path), triggers


def max_dd(path):
    peak = np.maximum.accumulate(path)
    return float(np.max((peak - path) / peak) * 100.0)


def main():
    ans = json.load(open(os.path.join(BASE, "data", "v09_comprehension_ANSWERS.json")))
    pred = ans["_prediction_for_the_equity_simulation"]

    say("=" * 78)
    say("V09 EQUITY-PATH SIMULATION — V09's own sizing rule, executed literally")
    say("=" * 78)
    say("NOT a test of an entry rule. V09 states none and none is invented (D-030).")
    say("Trade streams are PT-035's, regenerated by the same committed code and seed.")
    say(f"Starting balance {START:,.0f} (V09's own worked example), risk {RISK:.0%}.")
    say("")
    say("PREDICTIONS, committed at 97d2c1b before this file existed:")
    for k in ("P-E1", "P-E2", "P-E3", "P-E4"):
        say(f"  {k} [{pred[k]['confidence']}] {pred[k]['claim']}")
    say("")

    M.qa_gate()
    results = {}
    for arm in ("A", "B"):
        m1 = M.load_m1(arm)
        m15 = M.resample(m1, 15)
        lo, hi = M.DEV_START, M.DEV_END
        m1w, m15w = m1.slice(lo, hi), m15.slice(lo, hi)
        ex = np.zeros(len(m15w.tm), bool)
        ex1 = np.zeros(len(m1w.tm), bool)
        for d in P.EXCLUDE_DAYS:
            d0 = M.dt2m(d)
            ex |= (m15w.tm >= d0) & (m15w.tm < d0 + M.DAY)
            ex1 |= (m1w.tm >= d0) & (m1w.tm < d0 + M.DAY)
        m15w = M.Bars(m15w.tm[~ex], m15w.o[~ex], m15w.h[~ex], m15w.l[~ex], m15w.c[~ex], arm, 15)
        m1w = M.Bars(m1w.tm[~ex1], m1w.o[~ex1], m1w.h[~ex1], m1w.l[~ex1], m1w.c[~ex1], arm, 1)

        for tag, stop, target in P.GEOMETRIES:
            grid = M.TradeGrid(m1w, m15w, stop_pips=stop, target_pips=target)
            rng = np.random.default_rng(P.SEED)
            seqs, _, _ = P.build_sequences(grid, rng, P.ITERS, P.SEQ_LEN)
            dds, terms, trigs, wipes = [], [], [], 0
            for s in seqs:
                path, t = simulate(s, stop, target)
                dds.append(max_dd(path))
                terms.append(path[-1])
                trigs.append(t)
                wipes += (path[-1] <= 0)
            dds, terms, trigs = np.array(dds), np.array(terms), np.array(trigs)
            cell = f"{arm}{tag}"
            say("=" * 78)
            say(f"CELL {cell} — geometry -{int(stop)}/+{int(target)}, arm {arm}, "
                f"{len(seqs)} sequences x {P.SEQ_LEN} trades")
            say("=" * 78)
            say(f"  4-loss recalculation trigger fired at least once: "
                f"{(trigs>0).mean()*100:.1f}% of sequences   "
                f"(median count {np.median(trigs):.0f}, max {trigs.max()})")
            say(f"  max peak-to-trough drawdown: median {np.median(dds):.1f}%   "
                f"5-95% [{np.percentile(dds,5):.1f}%, {np.percentile(dds,95):.1f}%]")
            say(f"     fraction of sequences exceeding 8%: {(dds>8.0).mean()*100:.1f}%")
            say(f"  terminal equity: median {np.median(terms):,.0f}   "
                f"5-95% [{np.percentile(terms,5):,.0f}, {np.percentile(terms,95):,.0f}]")
            say(f"     fraction ending BELOW the {START:,.0f} start: "
                f"{(terms<START).mean()*100:.1f}%")
            say(f"  fully wiped out (terminal <= 0): {wipes} of {len(seqs)}")
            say("")
            results[cell] = {
                "n_seq": int(len(seqs)),
                "trigger_fired_frac": float((trigs > 0).mean()),
                "trigger_median": float(np.median(trigs)),
                "trigger_max": int(trigs.max()),
                "dd_median": float(np.median(dds)),
                "dd_5_95": [float(np.percentile(dds, 5)), float(np.percentile(dds, 95))],
                "dd_over8_frac": float((dds > 8.0).mean()),
                "term_median": float(np.median(terms)),
                "term_below_start_frac": float((terms < START).mean()),
                "wipeouts": int(wipes),
            }

    say("=" * 78)
    say("PREDICTIONS, SCORED")
    say("=" * 78)
    e1 = all(v["trigger_fired_frac"] > 0.5 for v in results.values())
    e2 = all(v["dd_over8_frac"] > 0.5 for v in results.values())
    e3 = all(v["term_median"] < START for v in results.values())
    e4 = all(v["wipeouts"] == 0 for v in results.values())
    for k, ok, note in (
        ("P-E1", e1, "trigger fires on a majority of sequences: "
         + ", ".join(f"{c}={v['trigger_fired_frac']*100:.0f}%" for c, v in results.items())),
        ("P-E2", e2, "drawdown exceeds 8% in the great majority: "
         + ", ".join(f"{c}={v['dd_over8_frac']*100:.0f}%" for c, v in results.items())),
        ("P-E3", e3, "median terminal below start: "
         + ", ".join(f"{c}={v['term_median']:,.0f}" for c, v in results.items())),
        ("P-E4", e4, "no wipeouts: "
         + ", ".join(f"{c}={v['wipeouts']}" for c, v in results.items())),
    ):
        say(f"  {k}: {'RIGHT' if ok else 'WRONG'} — {note}")
    say("")
    say("SCOPE: this executes V09's stated sizing rule on matched-random entries.")
    say("It says nothing about the method's entries, which V09 does not supply.")

    results["predictions"] = {"P-E1": bool(e1), "P-E2": bool(e2),
                              "P-E3": bool(e3), "P-E4": bool(e4)}
    out = os.path.join(BASE, "data", "equity_path_output.txt")
    with open(out, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    with open(os.path.join(BASE, "data", "equity_path_results.json"), "w") as fh:
        json.dump(results, fh, indent=2)
    print(f"\nwrote {out}")


if __name__ == "__main__":
    main()
